---

- name: Make sure the directories exist
  file:
    path: "{{ item | dirname }}"
    owner: "{{ ssl_cert_owner_dir }}"
    group: "{{ ssl_cert_group_dir }}"
    mode: "{{ ssl_cert_mode_dir }}"
    state: directory
  when: >
    item != None
  with_items:
    - "{{ ssl_cert_server_key_file }}"
    - "{{ ssl_cert_server_cert_file }}"
    - "{{ ssl_cert_ca_cert_file }}"

- name: Install the Server key
  copy:
    dest: "{{ ssl_cert_server_key_file }}"
    content: "{{
        (ssl_cert_server_key + ssl_cert_ca_cert)
            if (
                ssl_cert_server_cert_bundle and
                ssl_cert_ca_cert != None and
                ssl_cert_ca_cert | length > 0)
            else
        ssl_cert_server_key }}"
    owner: "{{ ssl_cert_owner_file }}"
    group: "{{ ssl_cert_group_file }}"
    mode: "{{ ssl_cert_mode_file }}"
  when: >
    ssl_cert_server_key_file != None and
    ssl_cert_server_key != None and
    ssl_cert_server_key | length > 0
  notify: Restart SSL service
  tags:
    - ssl_cert_server_key

- name: Install the Server certificate
  copy:
    dest: "{{ ssl_cert_server_cert_file }}"
    content: "{{ ssl_cert_server_cert }}"
    owner: "{{ ssl_cert_owner_file }}"
    group: "{{ ssl_cert_group_file }}"
    mode: "{{ ssl_cert_mode_file }}"
  when: >
    ssl_cert_server_cert_file != None and
    ssl_cert_server_cert != None and
    ssl_cert_server_cert | length > 0
  notify: Restart SSL service
  tags:
    - ssl_cert_server_cert

- name: Install the CA certificate
  copy:
    dest: "{{ ssl_cert_ca_cert_file }}"
    content: "{{ ssl_cert_ca_cart }}"
    owner: "{{ ssl_cert_owner_file }}"
    group: "{{ ssl_cert_group_file }}"
    mode: "{{ ssl_cert_mode_file }}"
  when: >
    not ssl_cert_server_cert_bundle and
    ssl_cert_ca_cert_file != None and
    ssl_cert_ca_cert != None and
    ssl_cert_ca_cert | length > 0
  notify: Restart SSL service
  tags:
    - ssl_cert_ca_cert
